### ISSUE TITLE
Stetho show a same result to both processes

### ISSUE THREAD

**Issue by hayden-han** [uPhyca/stetho-realm#28]
hi, i use a realm to my lockscreen app. before the start, i'm sorry to my english is not good T-T.

my app have a 2 process, app process and another process(it has a different app process id).
the problem when using stetho, it show same result to both app process and another process.

I write a data to ream. my app process update realm database and this update don't effect my another process realm database(i guess why it is forked. so once it was copy once when another process was created). so it's ok. natural. but i use a stetho, it show same result, althought anther process's realm db is not changed. 

i hope that u can understand what i say :)

**Comment by zaki50** [comment]
Current Realm does not support multi process.
**PLEASE DO NO USE** same realm database file from multiple processes.

I guess a commit in one process does not trigger updating live objects in another process.
That's why you don't see the changed in another process.

Stetho-Realm always reads latest data in the database file and seeing the same data is normal if you are using the same database file.
